services:
  web:
    container_name: personality-test-web
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - '${WEB_PORT:-3000}:3000'
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DB_URL=${DB_URL_DOCKER:-mongodb://${DB_USERNAME}:${DB_PASSWORD}@mongodb:27017/${DB_NAME:-b5}?authSource=admin}
      - DB_NAME=${DB_NAME:-b5}
      - DB_COLLECTION=${DB_COLLECTION:-results}
      - NEXT_PUBLIC_ENV=${NEXT_PUBLIC_ENV:-production}
      - NEXT_PUBLIC_ANALYTICS_ID=${NEXT_PUBLIC_ANALYTICS_ID:-}
    depends_on:
      - mongodb

  mongodb:
    container_name: personality-test-mongodb
    image: mongo
    restart: unless-stopped
    ports:
      - '${DB_PORT:-27017}:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
